### ISSUE TITLE
TempTest.java should be a real test

### ISSUE THREAD

**Issue by bradh** [ngageoint/geopackage-tiff-java#2]
That code should be in a parallel test directory, and refer to available test data.

**Comment by bosborn** [comment]
You are catching this library still in development in its first few days.  Version 1 is not yet released.  TempTest will not be released and some tests will be added.

**Comment by bosborn** [comment]
Moved to the test section for now, will be deleted later.

**Comment by bradh** [comment]
No problem. Just showing the excitement :-)

**Comment by bosborn** [comment]
TempTest is officially deleted.  Added read and write tests with test files.  Added a command line test application to read and print info from a TIFF file (TiffFileTester).

Released version 1.0.0 which is in the central repo.
